### ISSUE TITLE
Tag renaming failed

### ISSUE THREAD

**Issue by Zodiase** [Zodiase/my-inventory-app#35]
This happened with a deployed instance.

<img width="1145" alt="image" src="https://github.com/Zodiase/my-inventory-app/assets/1815174/f3da18dd-60eb-486c-9078-7672bdbf42a1">

Need to investigate.

**Comment by Zodiase** [comment]
Error log from server side:

```
I20230728-18:07:56.290(-7)? [api/tags] renameTag <= {
I20230728-18:07:56.291(-7)?   'tag._id': '[string]xdGwZXPDareeeqRMf',
I20230728-18:07:56.292(-7)?   'tag.name': '[string]Barfoo',
I20230728-18:07:56.292(-7)?   'tag.parentTagId': '[string]',
I20230728-18:07:56.292(-7)?   'tag.createdAt': '[printable object]Sun Jul 23 2023 01:07:03 GMT-0700 (Pacific Daylight Time)',
I20230728-18:07:56.293(-7)?   'tag.modifiedAt': '[printable object]Sun Jul 23 2023 01:07:03 GMT-0700 (Pacific Daylight Time)',
I20230728-18:07:56.293(-7)?   'tag.path.0._id': '[string]',
I20230728-18:07:56.293(-7)?   'tag.path.0.name': '[string]Barfoo',
I20230728-18:07:56.293(-7)?   newName: '[string]Barfoo-1'
I20230728-18:07:56.293(-7)? }
I20230728-18:07:56.444(-7)? Exception while invoking method 'renameTag' MongoServerError: The positional operator did not find the match needed from the query.
I20230728-18:07:56.445(-7)?     at ~/.meteor/packages/npm-mongo/.4.16.0.7p84qk.nobl2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/operations/update.js:72:33
I20230728-18:07:56.445(-7)?     at ~/.meteor/packages/npm-mongo/.4.16.0.7p84qk.nobl2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection_pool.js:333:25
I20230728-18:07:56.445(-7)?     at ~/.meteor/packages/npm-mongo/.4.16.0.7p84qk.nobl2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/sdam/server.js:210:17
I20230728-18:07:56.446(-7)?     at handleOperationResult (~/.meteor/packages/npm-mongo/.4.16.0.7p84qk.nobl2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/sdam/server.js:326:20)
I20230728-18:07:56.446(-7)?     at Connection.onMessage (~/.meteor/packages/npm-mongo/.4.16.0.7p84qk.nobl2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection.js:243:9)
I20230728-18:07:56.446(-7)?     at MessageStream.<anonymous> (~/.meteor/packages/npm-mongo/.4.16.0.7p84qk.nobl2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection.js:61:60)
I20230728-18:07:56.447(-7)?     at MessageStream.emit (events.js:400:28)
I20230728-18:07:56.447(-7)?     at MessageStream.emit (domain.js:475:12)
I20230728-18:07:56.448(-7)?     at processIncomingData (~/.meteor/packages/npm-mongo/.4.16.0.7p84qk.nobl2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
I20230728-18:07:56.448(-7)?     at MessageStream._write (~/.meteor/packages/npm-mongo/.4.16.0.7p84qk.nobl2++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
I20230728-18:07:56.451(-7)?     at writeOrBuffer (internal/streams/writable.js:358:12)
I20230728-18:07:56.451(-7)?     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
I20230728-18:07:56.452(-7)?     at Socket.ondata (internal/streams/readable.js:731:22)
I20230728-18:07:56.453(-7)?     at Socket.emit (events.js:400:28)
I20230728-18:07:56.453(-7)?     at Socket.emit (domain.js:475:12)
I20230728-18:07:56.453(-7)?     at addChunk (internal/streams/readable.js:293:12)
I20230728-18:07:56.453(-7)?  => awaited here:
I20230728-18:07:56.453(-7)?     at Function.Promise.await (~/.meteor/packages/promise/.0.12.2.10rpwz8.122b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20230728-18:07:56.453(-7)?     at imports/api/tags.ts:111:20
I20230728-18:07:56.453(-7)?     at ~/.meteor/packages/promise/.0.12.2.10rpwz8.122b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20230728-18:07:56.453(-7)?  => awaited here:
I20230728-18:07:56.454(-7)?     at Function.Promise.await (~/.meteor/packages/promise/.0.12.2.10rpwz8.122b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20230728-18:07:56.454(-7)?     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:781:32)
I20230728-18:07:56.454(-7)?     at packages/meteor.js:365:18
I20230728-18:07:56.454(-7)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
I20230728-18:07:56.454(-7)?     at packages/ddp-server/livedata_server.js:791:46
I20230728-18:07:56.454(-7)?     at new Promise (<anonymous>)
I20230728-18:07:56.454(-7)?     at Session.method (packages/ddp-server/livedata_server.js:739:23)
I20230728-18:07:56.454(-7)?     at packages/ddp-server/livedata_server.js:603:43
```

**Comment by Zodiase** [comment]
Selector used for update operation:

```
I20230728-18:14:04.370(-7)? [api/tags] selector {
I20230728-18:14:04.371(-7)?   _id: '[string]xdGwZXPDareeeqRMf',
I20230728-18:14:04.371(-7)?   createdAt: '[printable object]Sun Jul 23 2023 01:07:03 GMT-0700 (Pacific Daylight Time)',
I20230728-18:14:04.371(-7)?   modifiedAt: '[printable object]Sun Jul 23 2023 01:07:03 GMT-0700 (Pacific Daylight Time)',
I20230728-18:14:04.371(-7)?   name: '[string]Barfoo',
I20230728-18:14:04.371(-7)?   '$or.0.path._id.$exists': '[boolean]false',
I20230728-18:14:04.371(-7)?   '$or.1.path._id.$exists': '[boolean]true',
I20230728-18:14:04.371(-7)?   '$or.1.path._id.$in.0': '[string]',
I20230728-18:14:04.371(-7)?   '$or.1.path._id.$in.1': '[string]xdGwZXPDareeeqRMf'
I20230728-18:14:04.371(-7)? }
```
